### ISSUE TITLE
Why isn't the newest version on F-Droid?

### ISSUE THREAD

**Issue by e3b** [TheTorProject/ooniprobe-android#91] opened 2017-05-27 20:34 UTC
I can't infer from the [F-Droid wiki page](https://f-droid.org/wiki/page/org.openobservatory.ooniprobe) what the problem is.

**Comment by hellais** [comment] 2017-05-28 03:52
The issue I guess is that we haven't yet forward ported the changes needed for the f-droid version (removal of fabric backtraces) to 1.1.4 and f-droid cannot build it.

I think @bassosimone and @lorenzoPrimi may have further comments.

Q: Is there some way we can streamline the f-droid release process so that f-droid people can more easily build new versions of ooniprobe from our tagged version without us having to every time forward port the fixes?

**Comment by bassosimone** [comment] 2017-07-31 05:51
Hello @e3b! So, I have now forward ported the changes and tagged `v1.1.4` for `f-droid`. In this case, it was not actually complex technically to forward port the changes. Reflecting on what went wrong, it was probably that this task slipped off my radar. *Action item*:

- [ ] we should probably define a release checklist.

Hello @hellais! So,

> Q: Is there some way we can streamline the f-droid release process so that f-droid people can more easily build new versions of ooniprobe from our tagged version without us having to every time forward port the fixes?

The diff wrt master is basically a diff that strips off all the non-free components we're using in the process, such as fabric and (upcoming!) firebase. As such, I don't immediately see how this could be completely automated.

It may probably help to structure the code such that all non-free code is inside the same package and there are very few references to it around. This may help to keep the diff small: one basically needs to nuke a specific package and then adjust the few other lines.

A thing that is a bit annoying is that, I guess because of `LC_ALL` settings, the `app/app.iml` file changes whenever @lorenzoPrimi commits or I commit. [On stackoverflow](https://stackoverflow.com/questions/25504982/is-it-mandatory-to-save-iml-files-in-version-control#comment58979376_25504982) I am reading this insightful comment:

> In latest Android Studio  (1.5.1) when you create a new Android project from scratch, the Android  Studio creates .gitignore file automatically and adds *.iml in  .gitignore. So now in 2016 the the answer would be "No, its not  mandatory to save .iml files in Version Control System."
 
Which means: *action item*:

- [ ] delete `*.iml` from the repository and add `*.iml` to `.gitignore`.

I will now try to forward port `v1.1.5-beta` (or is it still `alpha`?) to the `f-droid` branch and see whether I have further comments and suggestions on how we can improve the process.

**Comment by bassosimone** [comment] 2017-07-31 06:43
Further thoughts after I forward ported f-droid to v1.1.5-alpha.2 (see: #98):

- it *may* help to have components related to *nonfree* dependencies in a package named *nonfree* or something like that (one knows that everything below that packages must be nuked, so one does not even need to *think* whether something should or should not be nuked)

- (I guess this is obvious) future third-party dependencies that are core to our activities should be opensource unless it's impossible to do so, to ease the forward porting process

- in `xml` and `build.gradle` files, it may help to have comments like `BEGIN NONFREE` and `END NONFREE` to delimit bits related to nonfree dependencies; again this would help the merge

- orchestration is not going to work on `fdroid` because we're using firebase. I wonder whether we can implement orchestration for fdroid as a process that wakeup when the network changes (I believe we can listen to this using free components) and receives somehow the notification back using HTTPS (this is probably how we want to do this for desktop anyway). RFC: @hellais 

- it would be nice to know (<- i.e. I need to research this) whether f-droid provides automatic tools to scan the build and see whether there are nonfree components inside it

**Comment by bassosimone** [comment] 2017-07-31 06:45
Well, I think I did dive into this topic enough, for now. Leaving this ticket open for comments.

**Comment by bassosimone** [comment] 2017-07-31 12:46
Uhm: I wanted to change the ticket now, but now I realize the latest version is not on f-droid yet. I wonder whether there is something else I should do, or whether I should just wait :-).

**Comment by bassosimone** [comment] 2017-08-11 10:02
After doing another round of porting, I can confirm the most difficult part of it is making sure the `AndroidManifest.xml` is the more difficult part to merge. It would help to have all non-free parts grouped together and marked as `<!-- BEGIN NONFREE --> ... <!-- END NONFREE -->` so to more easily know what can be ripped and what should instead be retained.

**Comment by bassosimone** [comment] 2017-08-11 10:03
Regarding availability of the next version on `f-droid` &mdash; which was the OP question &mdash; I have just tagged `v1.1.5-fdroid` and @hellais asked on IRC `#fdroid` to pull this change. Let's wait.

**Comment by bassosimone** [comment] 2017-08-16 11:22
Uhm, as reported also on slack and IRC, it seems on f-droid we're still at v1.1.3, despite having tagged v1.1.5-fdroid a few days ago. I wonder if there is something we can do to make more smooth the process of integrating our new releases into f-droid. Maybe @eighthave can provide good suggestions here? (I am tagging you because you helped us to land our initial release on f-droid).

**Comment by relan** [comment] 2017-08-27 06:47
The problem with v1.1.5 on F-Droid is that it uses `constraint-layout:1.0.0-alpha7`. F-Droid usually does not have pre-release versions of tools and libraries. I've added a [hack](https://gitlab.com/fdroid/fdroiddata/commit/7a1f9f1d1c33613dbb70d500f73d2b7cb7f955c8) to make it build. Please bump `constraint-layout` version for the next release.

**Comment by eighthave** [comment] 2017-08-29 10:44
A lot of alpha/beta release libraries from Google are released with
Google's non-free "Preview" license, that's why they are not used by
F-Droid.

**Comment by bassosimone** [comment] 2017-09-02 16:00
@relan: Thank you! I have already fix the issue in 7fedaef3aea43e74c6f. We'll try to keep in mind that using pre-release versions create issues to f-droid and avoid doing this in the future.

I have tagged `v1.1.5-fdroid.1` that uses `constraint-layout:1.0.2`.

@eighthave: Ah, I understand! Thanks for further clarifying the reationale!

I guess we can now close this issue, since the latest version has landed on f-droid!

**Closed by bassosimone** 2017-09-02 16:00 UTC
Labels: bug

**Comment by relan** [comment] 2017-09-02 16:26
Updated in https://gitlab.com/fdroid/fdroiddata/commit/a19e2b814538fa4fe0379972ca555c17b9caf8ed

I've also enabled auto-updating. Note that it works only when Git tag (e.g. v1.2-fdroid) corresponds to versionName in build.gradle (1.2-fdroid, without "v") and has `-fdroid` in it.

**Comment by bassosimone** [comment] 2017-09-04 12:46
> Note that it works only when Git tag (e.g. v1.2-fdroid) corresponds to versionName in build.gradle (1.2-fdroid, without "v") and has -fdroid in it.

Thanks! I'll keep this in mind!

**Comment by genofire** [comment] 2018-01-28 23:56
Again?

**Comment by hellais** [comment] 2018-01-29 06:25
Hi @genofire yeah, we have been pretty bad at keeping up to date the version of OONI Probe in F-Droid.

Help in keeping the F-Droid version in up to date would be greatly appreciated 👍

**Comment by eighthave** [comment] 2018-01-29 20:46
If you just tag with the right tag format, F-Droid will automatically
update.  Or even better, make the same release tag build on F-Droid,
then they'll be in sync.  That's how projects usually do it.

**Comment by hellais** [comment] 2018-02-05 14:41
The main issue with keeping it up to date has been forward porting all the patches that we need to apply to the OONI Probe software to remove all the non-free dependencies to make it fit within the F-Droid policy.

This is unfortunately a semi-manual process that require some non-trivial amount of time to do and test that nothing breaks.

It would be great if we could get somebody to help us with this and ensure that when we make a new OONI Probe release everything in the F-Droid branch is working as expected.

What would be even better, is doing some work on getting OONI Probe in a shape where the non-free dependencies are optional and we can just disable them with some compile time flags.

**Comment by IzzySoft** [comment] 2018-06-26 12:30
Did you miss to tag `v1.3.2-fdroid`, or is that flavor not yet ready? The bot won't pick up the new release without that.
