### ISSUE TITLE
[Request] Check Signal Messenger

### ISSUE THREAD

**Issue by zero77** [TheTorProject/ooniprobe-android#147] opened 2018-04-16 12:38 UTC
Can you please also add Signal messenger in the instant messaging checking section.
Thanks

**Comment by hellais** [comment] 2018-04-16 13:27
Hi, thanks for your interest in OONI Probe.

We have are tracking the creating of a Signal IM test inside of this issue already: https://github.com/measurement-kit/measurement-kit/issues/1396, as the test would first have to be part of Measurement Kit our network measurement library.

Developing a new Instant Messaging test actually requires a fair amount of effort, especially without support/input from the app developers themselves.

We can't really anticipate currently, when, and if, we are going to add support for testing the signal app, though if there were interest from the Signal developers to support this test (cc @moxie0 @charlesmchen @signalapp) that may change.

I am going to close this ticket for the moment as it's a duplicate of: https://github.com/measurement-kit/measurement-kit/issues/1396. If there is interest in developing a Signal test, discussion should proceed over there.

**Closed by hellais** 2018-04-16 13:27 UTC
