### ISSUE TITLE
Communicate max_runtime meaning more clearly

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooniprobe-android#50] opened 2017-02-08 19:43 UTC
#### Description
Setting a value to the max runtime option has no effect.

#### Steps to reproduce
Set any positive integer to the max runtime option (in advanced settings).

#### Expected behaviour
Test runtime should adhere to the max runtime setting.

#### Actual behavior
Test runtime is not in accordance with the max runtime setting.

**Comment by lorenzoPrimi** [comment] 2017-02-09 17:48
Can you provide more information on how to reproduce this bug?
We haven't been able to find it.

**Comment by bassosimone** [comment] 2017-02-09 23:11
@anadahz consider that the amount of time you specify cannot be honoured strictly (or, it is not *easy* at all to do that). The easy thing that one guarantee, and we do guarantee that, is that *after* the deadline expires, no more test is scheduled. However, this means that possibly three tests are still running after the deadline, and this is a certain number of seconds.

Related to this (and that's why I'm tagging it usability and tagging @mrphs): *only* the tests that have an input list can honour this requirement of the maximum number of seconds. For tests that do not have input list (i.e. NDT and http-invalid-request-line) it does not make full sense to cap the execution because that would mean aborting the test in the middle. In such case, I think it would be more "usable" to provide the user with the possibility of *aborting* a running test.

**Comment by mrphs** [comment] 2017-02-09 23:34
I'd have loved to be of help here but unfortunately I don't have an android and without actually using it, it's hard to comment on the UX :/ sorry!

**Comment by anadahz** [comment] 2017-02-10 11:36
@bassosimone makes sense a better wording of the setting will make more sense to the user like and a note that this option has effect in tests that have input (i.e web_connectivity)
However even in web connectivity test the runtime limit is not being honored.

To reproduce it set the `Max runtime` option to 1 second and run the `Web Connectivity` test.
In my tests there are (always) 3 inputs being tested with test_runtime ~1 second per input, whereas some inputs (usually the last) reaching even >2.5 seconds.

**Comment by lorenzoPrimi** [comment] 2017-02-11 18:35
We can solve this by setting a minimum allowed value of 10 seconds. If any lower value is entered will default to the minimum value and show a toast explaining the reason.

**Comment by lorenzoPrimi** [comment] 2017-02-14 09:28
@hellais can you provide me this string?
I thought of something like "The max runtime you have entered is too low, setting to default."

**Comment by hellais** [comment] 2017-04-05 16:48
I believe this is now fixed by displaying a toast saying that we will set it to a default value when the runtime is too low.

**Closed by hellais** 2017-04-05 16:48 UTC
Labels: usability
